# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /cvmfs/sft.cern.ch/lcg/releases/CMake/3.26.2-0664a/x86_64-el9-gcc12-opt/bin/cmake

# The command to remove a file.
RM = /cvmfs/sft.cern.ch/lcg/releases/CMake/3.26.2-0664a/x86_64-el9-gcc12-opt/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /afs/cern.ch/work/f/faguo/Grainita/example_Fangyi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /afs/cern.ch/work/f/faguo/Grainita/example_Fangyi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.26.2-0664a/x86_64-el9-gcc12-opt/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.26.2-0664a/x86_64-el9-gcc12-opt/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /afs/cern.ch/work/f/faguo/Grainita/example_Fangyi/CMakeFiles /afs/cern.ch/work/f/faguo/Grainita/example_Fangyi//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /afs/cern.ch/work/f/faguo/Grainita/example_Fangyi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named Simulation

# Build rule for target.
Simulation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Simulation
.PHONY : Simulation

# fast build rule for target.
Simulation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Simulation.dir/build.make CMakeFiles/Simulation.dir/build
.PHONY : Simulation/fast

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.s
.PHONY : main.cc.s

src/MyEventAction.o: src/MyEventAction.cc.o
.PHONY : src/MyEventAction.o

# target to build an object file
src/MyEventAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/MyEventAction.cc.o
.PHONY : src/MyEventAction.cc.o

src/MyEventAction.i: src/MyEventAction.cc.i
.PHONY : src/MyEventAction.i

# target to preprocess a source file
src/MyEventAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/MyEventAction.cc.i
.PHONY : src/MyEventAction.cc.i

src/MyEventAction.s: src/MyEventAction.cc.s
.PHONY : src/MyEventAction.s

# target to generate assembly for a file
src/MyEventAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/MyEventAction.cc.s
.PHONY : src/MyEventAction.cc.s

src/MySteppingAction.o: src/MySteppingAction.cc.o
.PHONY : src/MySteppingAction.o

# target to build an object file
src/MySteppingAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/MySteppingAction.cc.o
.PHONY : src/MySteppingAction.cc.o

src/MySteppingAction.i: src/MySteppingAction.cc.i
.PHONY : src/MySteppingAction.i

# target to preprocess a source file
src/MySteppingAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/MySteppingAction.cc.i
.PHONY : src/MySteppingAction.cc.i

src/MySteppingAction.s: src/MySteppingAction.cc.s
.PHONY : src/MySteppingAction.s

# target to generate assembly for a file
src/MySteppingAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/MySteppingAction.cc.s
.PHONY : src/MySteppingAction.cc.s

src/action.o: src/action.cc.o
.PHONY : src/action.o

# target to build an object file
src/action.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/action.cc.o
.PHONY : src/action.cc.o

src/action.i: src/action.cc.i
.PHONY : src/action.i

# target to preprocess a source file
src/action.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/action.cc.i
.PHONY : src/action.cc.i

src/action.s: src/action.cc.s
.PHONY : src/action.s

# target to generate assembly for a file
src/action.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/action.cc.s
.PHONY : src/action.cc.s

src/analysis.o: src/analysis.cc.o
.PHONY : src/analysis.o

# target to build an object file
src/analysis.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/analysis.cc.o
.PHONY : src/analysis.cc.o

src/analysis.i: src/analysis.cc.i
.PHONY : src/analysis.i

# target to preprocess a source file
src/analysis.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/analysis.cc.i
.PHONY : src/analysis.cc.i

src/analysis.s: src/analysis.cc.s
.PHONY : src/analysis.s

# target to generate assembly for a file
src/analysis.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/analysis.cc.s
.PHONY : src/analysis.cc.s

src/construction.o: src/construction.cc.o
.PHONY : src/construction.o

# target to build an object file
src/construction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/construction.cc.o
.PHONY : src/construction.cc.o

src/construction.i: src/construction.cc.i
.PHONY : src/construction.i

# target to preprocess a source file
src/construction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/construction.cc.i
.PHONY : src/construction.cc.i

src/construction.s: src/construction.cc.s
.PHONY : src/construction.s

# target to generate assembly for a file
src/construction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/construction.cc.s
.PHONY : src/construction.cc.s

src/detector.o: src/detector.cc.o
.PHONY : src/detector.o

# target to build an object file
src/detector.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detector.cc.o
.PHONY : src/detector.cc.o

src/detector.i: src/detector.cc.i
.PHONY : src/detector.i

# target to preprocess a source file
src/detector.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detector.cc.i
.PHONY : src/detector.cc.i

src/detector.s: src/detector.cc.s
.PHONY : src/detector.s

# target to generate assembly for a file
src/detector.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detector.cc.s
.PHONY : src/detector.cc.s

src/generator.o: src/generator.cc.o
.PHONY : src/generator.o

# target to build an object file
src/generator.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/generator.cc.o
.PHONY : src/generator.cc.o

src/generator.i: src/generator.cc.i
.PHONY : src/generator.i

# target to preprocess a source file
src/generator.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/generator.cc.i
.PHONY : src/generator.cc.i

src/generator.s: src/generator.cc.s
.PHONY : src/generator.s

# target to generate assembly for a file
src/generator.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/generator.cc.s
.PHONY : src/generator.cc.s

src/physics.o: src/physics.cc.o
.PHONY : src/physics.o

# target to build an object file
src/physics.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/physics.cc.o
.PHONY : src/physics.cc.o

src/physics.i: src/physics.cc.i
.PHONY : src/physics.i

# target to preprocess a source file
src/physics.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/physics.cc.i
.PHONY : src/physics.cc.i

src/physics.s: src/physics.cc.s
.PHONY : src/physics.s

# target to generate assembly for a file
src/physics.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/physics.cc.s
.PHONY : src/physics.cc.s

src/tracking.o: src/tracking.cc.o
.PHONY : src/tracking.o

# target to build an object file
src/tracking.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/tracking.cc.o
.PHONY : src/tracking.cc.o

src/tracking.i: src/tracking.cc.i
.PHONY : src/tracking.i

# target to preprocess a source file
src/tracking.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/tracking.cc.i
.PHONY : src/tracking.cc.i

src/tracking.s: src/tracking.cc.s
.PHONY : src/tracking.s

# target to generate assembly for a file
src/tracking.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/tracking.cc.s
.PHONY : src/tracking.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Simulation"
	@echo "... main"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/MyEventAction.o"
	@echo "... src/MyEventAction.i"
	@echo "... src/MyEventAction.s"
	@echo "... src/MySteppingAction.o"
	@echo "... src/MySteppingAction.i"
	@echo "... src/MySteppingAction.s"
	@echo "... src/action.o"
	@echo "... src/action.i"
	@echo "... src/action.s"
	@echo "... src/analysis.o"
	@echo "... src/analysis.i"
	@echo "... src/analysis.s"
	@echo "... src/construction.o"
	@echo "... src/construction.i"
	@echo "... src/construction.s"
	@echo "... src/detector.o"
	@echo "... src/detector.i"
	@echo "... src/detector.s"
	@echo "... src/generator.o"
	@echo "... src/generator.i"
	@echo "... src/generator.s"
	@echo "... src/physics.o"
	@echo "... src/physics.i"
	@echo "... src/physics.s"
	@echo "... src/tracking.o"
	@echo "... src/tracking.i"
	@echo "... src/tracking.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

