
/random/setSeeds 123456 789012

/run/numberOfThreads 4

/run/setCut 0.1 mm

/run/verbose 1
/event/verbose 0
/tracking/verbose 0

# Detector construction
/detector/pitchSize 7 mm
/detector/fiberNum 56
/detector/ZSegNum 25

/run/initialize

# Set particle gun
/gps/particle gamma
/gps/energy 10 GeV
/gps/direction 0 0 1
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/centre 0 0 -50 cm
/gps/pos/halfx 2.5 cm
/gps/pos/halfy 2.5 cm


# Run event number
/run/beamOn 10000
